<a href="https://colab.research.google.com/github/rhkhandu/rhkhandu/blob/main/First_in_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [28]:
gdp_data = pd.read_csv('/content/drive/MyDrive/Data Set/gapminder_gdp_asia.csv')

In [34]:
world_dev_index = pd.read_excel('/content/drive/MyDrive/Data Set/Data_Extract_From_World_Development_Indicators.xlsx')

In [35]:
world_dev_index

,Country Name,Time,GDP per capita (constant 2010 US$),CO2 emissions (metric tons per capita)
0,Bangladesh,2006.0,649.929885,0.309163
1,Bangladesh,2007.0,687.323086,0.312206
2,Bangladesh,2008.0,720.357004,0.343895
3,Bangladesh,2009.0,748.296060,0.373297
4,Bangladesh,2010.0,781.153594,0.408084
...,...,...,...,...
88,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN
91,Data from database: World Development Indicators,NaN,NaN,NaN
92,Last Updated: 10/07/2020,NaN,NaN,NaN

In [36]:
world_dev_index.head()

,Country Name,Time,GDP per capita (constant 2010 US$),CO2 emissions (metric tons per capita)
0,Bangladesh,2006.0,649.929885,0.309163
1,Bangladesh,2007.0,687.323086,0.312206
2,Bangladesh,2008.0,720.357004,0.343895
3,Bangladesh,2009.0,748.296060,0.373297
4,Bangladesh,2010.0,781.153594,0.408084

In [37]:
world_dev_index.tail()

,Country Name,Time,GDP per capita (constant 2010 US$),CO2 emissions (metric tons per capita)
88,NaN,NaN,NaN,NaN
89,NaN,NaN,NaN,NaN
90,NaN,NaN,NaN,NaN
91,Data from database: World Development Indicators,NaN,NaN,NaN
92,Last Updated: 10/07/2020,NaN,NaN,NaN

In [40]:
world_dev_index.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 4 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Country Name                            90 non-null     object
 1   Time                                    88 non-null     float64
 2   GDP per capita (constant 2010 US$)      88 non-null     float64
 3   CO2 emissions (metric tons per capita)  88 non-null     float64
dtypes: float64(3), object(1)
memory usage: 3.0+ KB

In [29]:
gdp_data

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Afghanistan,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338
1,Bahrain,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340
2,Bangladesh,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792
3,Cambodia,368.469286,434.038336,496.913648,523.432314,421.624026,524.972183,624.475478,683.895573,682.303175,734.285170,896.226015,1713.778686
4,China,400.448611,575.987001,487.674018,612.705693,676.900092,741.237470,962.421381,1378.904018,1655.784158,2289.234136,3119.280896,4959.114854
5,Hong Kong China,3054.421209,3629.076457,4692.648272,6197.962814,8315.928145,11186.141250,14560.530510,20038.472690,24757.603010,28377.632190,30209.015160,39724.978670
6,India,546.565749,590.061996,658.347151,700.770611,724.032527,813.337323,855.723538,976.512676,1164.406809,1458.817442,1746.769454,2452.210407
7,Indonesia,749.681655,858.900271,849.289770,762.431772,1111.107907,1382.702056,1516.872988,1748.356961,2383.140898,3119.335603,2873.912870,3540.651564
8,Iran,3035.326002,3290.257643,4187.329802,5906.731805,9613.818607,11888.595080,7608.334602,6642.881371,7235.653188,8263.590301,9240.761975,11605.714490
9,Iraq,4129.766056,6229.333562,8341.737815,8931.459811,9576.037596,14688.235070,14517.907110,11643.572680,3745.640687,3076.239795,4390.717312,4471.061906
10,Israel,4086.522128,5385.278451,7105.630706,8393.741404,12786.932230,13306.619210,15367.029200,17122.479860,18051.522540,20896.609240,21905.595140,25523.277100
11,Japan,3216.956347,4317.694365,6576.649461,9847.788607,14778.786360,16610.377010,19384.105710,22375.941890,26824.895110,28816.584990,28604.591900,31656.068060
12,Jordan,1546.907807,1886.080591,2348.009158,2741.796252,2110.856309,2852.351568,4161.415959,4448.679912,3431.593647,3645.379572,3844.917194,4519.461171
13,Korea Dem. Rep.,1088.277758,1571.134655,1621.693598,2143.540609,3701.621503,4106.301249,4106.525293,4106.492315,3726.063507,1690.756814,1646.758151,1593.065480
14,Korea Rep.,1030.592226,1487.593537,1536.344387,2029.228142,3030.876650,4657.221020,5622.942464,8533.088805,12104.278720,15993.527960,19233.988180,23348.139730
15,Kuwait,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,31354.035730,28118.429980,34932.919590,40300.619960,35110.105660,47306.989780
16,Lebanon,4834.804067,6089.786934,5714.560611,6006.983042,7486.384341,8659.696836,7640.519521,5377.091329,6890.806854,8754.963850,9313.938830,10461.058680
17,Malaysia,1831.132894,1810.066992,2036.884944,2277.742396,2849.094780,3827.921571,4920.355951,5249.802653,7277.912802,10132.909640,10206.977940,12451.655800
18,Mongolia,786.566857,912.662609,1056.353958,1226.041130,1421.741975,1647.511665,2000.603139,2338.008304,1785.402016,1902.252100,2140.739323,3095.772271
19,Myanmar,331.000000,350.000000,388.000000,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,415.000000,611.000000,944.000000
20,Nepal,545.865723,597.936356,652.396859,676.442225,674.788130,694.112440,718.373095,775.632450,897.740360,1010.892138,1057.206311,1091.359778
21,Oman,1828.230307,2242.746551,2924.638113,4720.942687,10618.038550,11848.343920,12954.791010,18115.223130,18616.706910,19702.055810,19774.836870,22316.192870
22,Pakistan,684.597144,747.083529,803.342742,942.408259,1049.938981,1175.921193,1443.429832,1704.686583,1971.829464,2049.350521,2092.712441,2605.947580
23,Philippines,1272.880995,1547.944844,1649.552153,1814.127430,1989.374070,2373.204287,2603.273765,2189.634995,2279.324017,2536.534925,2650.921068,3190.481016
24,Saudi Arabia,6459.554823,8157.591248,11626.419750,16903.048860,24837.428650,34167.762600,33693.175250,21198.261360,24841.617770,20586.690190,19014.541180,21654.831940
25,Singapore,2315.138227,2843.104409,3674.735572,4977.418540,8597.756202,11210.089480,15169.161120,18861.530810,24769.891200,33519.476600,36023.105400,47143.179640
26,Sri Lanka,1083.532030,1072.546602,1074.471960,1135.514326,1213.395530,1348.775651,1648.079789,1876.766827,2153.739222,2664.477257,3015.378833,3970.095407
27,Syria,1643.485354,2117.234893,2193.037133,1881.923632,2571.423014,3195.484582,3761.837715,3116.774285,3340.542768,4014.238972,4090.925331,4184.548089
28,Taiwan,1206.947913,1507.861290,1822.879028,2643.858681,4062.523897,5596.519826,7426.354774,11054.561750,15215.657900,20206.820980,23235.423290,28718.276840
29,Thailand,757.797418,793.577415,1002.199172,1295.460660,1524.358936,1961.224635,2393.219781,2982.653773,4616.896545,5852.625497,5913.187529,7458.396327
30,Vietnam,605.066492,676.285448,772.049160,637.123289,699.501644,713.537120,707.235786,820.799445,989.023149,1385.896769,1764.456677,2441.576404
31,West Bank and Gaza,1515.592329,1827.067742,2198.956312,2649.715007,3133.409277,3682.831494,4336.032082,5107.197384,6017.654756,7110.667619,4515.487575,3025.349798
32,Yemen Rep.,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906

In [24]:
gdp_data.head()

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Afghanistan,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338
1,Bahrain,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340
2,Bangladesh,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792
3,Cambodia,368.469286,434.038336,496.913648,523.432314,421.624026,524.972183,624.475478,683.895573,682.303175,734.285170,896.226015,1713.778686
4,China,400.448611,575.987001,487.674018,612.705693,676.900092,741.237470,962.421381,1378.904018,1655.784158,2289.234136,3119.280896,4959.114854

In [30]:
gdp_data.tail()

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
28,Taiwan,1206.947913,1507.861290,1822.879028,2643.858681,4062.523897,5596.519826,7426.354774,11054.561750,15215.657900,20206.820980,23235.423290,28718.276840
29,Thailand,757.797418,793.577415,1002.199172,1295.460660,1524.358936,1961.224635,2393.219781,2982.653773,4616.896545,5852.625497,5913.187529,7458.396327
30,Vietnam,605.066492,676.285448,772.049160,637.123289,699.501644,713.537120,707.235786,820.799445,989.023149,1385.896769,1764.456677,2441.576404
31,West Bank and Gaza,1515.592329,1827.067742,2198.956312,2649.715007,3133.409277,3682.831494,4336.032082,5107.197384,6017.654756,7110.667619,4515.487575,3025.349798
32,Yemen Rep.,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906

In [38]:
 gdp_data = pd.read_csv('/content/drive/MyDrive/Data Set/gapminder_gdp_asia.csv', index_col='country')

In [39]:
gdp_data

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
country,,,,,,,,,,,,
Afghanistan,779.445314,820.853030,853.100710,836.197138,739.981106,786.113360,978.011439,852.395945,649.341395,635.341351,726.734055,974.580338
Bahrain,9867.084765,11635.799450,12753.275140,14804.672700,18268.658390,19340.101960,19211.147310,18524.024060,19035.579170,20292.016790,23403.559270,29796.048340
Bangladesh,684.244172,661.637458,686.341554,721.186086,630.233627,659.877232,676.981866,751.979403,837.810164,972.770035,1136.390430,1391.253792
Cambodia,368.469286,434.038336,496.913648,523.432314,421.624026,524.972183,624.475478,683.895573,682.303175,734.285170,896.226015,1713.778686
China,400.448611,575.987001,487.674018,612.705693,676.900092,741.237470,962.421381,1378.904018,1655.784158,2289.234136,3119.280896,4959.114854
Hong Kong China,3054.421209,3629.076457,4692.648272,6197.962814,8315.928145,11186.141250,14560.530510,20038.472690,24757.603010,28377.632190,30209.015160,39724.978670
India,546.565749,590.061996,658.347151,700.770611,724.032527,813.337323,855.723538,976.512676,1164.406809,1458.817442,1746.769454,2452.210407
Indonesia,749.681655,858.900271,849.289770,762.431772,1111.107907,1382.702056,1516.872988,1748.356961,2383.140898,3119.335603,2873.912870,3540.651564
Iran,3035.326002,3290.257643,4187.329802,5906.731805,9613.818607,11888.595080,7608.334602,6642.881371,7235.653188,8263.590301,9240.761975,11605.714490
Iraq,4129.766056,6229.333562,8341.737815,8931.459811,9576.037596,14688.235070,14517.907110,11643.572680,3745.640687,3076.239795,4390.717312,4471.061906
Israel,4086.522128,5385.278451,7105.630706,8393.741404,12786.932230,13306.619210,15367.029200,17122.479860,18051.522540,20896.609240,21905.595140,25523.277100
Japan,3216.956347,4317.694365,6576.649461,9847.788607,14778.786360,16610.377010,19384.105710,22375.941890,26824.895110,28816.584990,28604.591900,31656.068060
Jordan,1546.907807,1886.080591,2348.009158,2741.796252,2110.856309,2852.351568,4161.415959,4448.679912,3431.593647,3645.379572,3844.917194,4519.461171
Korea Dem. Rep.,1088.277758,1571.134655,1621.693598,2143.540609,3701.621503,4106.301249,4106.525293,4106.492315,3726.063507,1690.756814,1646.758151,1593.065480
Korea Rep.,1030.592226,1487.593537,1536.344387,2029.228142,3030.876650,4657.221020,5622.942464,8533.088805,12104.278720,15993.527960,19233.988180,23348.139730
Kuwait,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,31354.035730,28118.429980,34932.919590,40300.619960,35110.105660,47306.989780
Lebanon,4834.804067,6089.786934,5714.560611,6006.983042,7486.384341,8659.696836,7640.519521,5377.091329,6890.806854,8754.963850,9313.938830,10461.058680
Malaysia,1831.132894,1810.066992,2036.884944,2277.742396,2849.094780,3827.921571,4920.355951,5249.802653,7277.912802,10132.909640,10206.977940,12451.655800
Mongolia,786.566857,912.662609,1056.353958,1226.041130,1421.741975,1647.511665,2000.603139,2338.008304,1785.402016,1902.252100,2140.739323,3095.772271
Myanmar,331.000000,350.000000,388.000000,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,415.000000,611.000000,944.000000
Nepal,545.865723,597.936356,652.396859,676.442225,674.788130,694.112440,718.373095,775.632450,897.740360,1010.892138,1057.206311,1091.359778
Oman,1828.230307,2242.746551,2924.638113,4720.942687,10618.038550,11848.343920,12954.791010,18115.223130,18616.706910,19702.055810,19774.836870,22316.192870
Pakistan,684.597144,747.083529,803.342742,942.408259,1049.938981,1175.921193,1443.429832,1704.686583,1971.829464,2049.350521,2092.712441,2605.947580
Philippines,1272.880995,1547.944844,1649.552153,1814.127430,1989.374070,2373.204287,2603.273765,2189.634995,2279.324017,2536.534925,2650.921068,3190.481016
Saudi Arabia,6459.554823,8157.591248,11626.419750,16903.048860,24837.428650,34167.762600,33693.175250,21198.261360,24841.617770,20586.690190,19014.541180,21654.831940
Singapore,2315.138227,2843.104409,3674.735572,4977.418540,8597.756202,11210.089480,15169.161120,18861.530810,24769.891200,33519.476600,36023.105400,47143.179640
Sri Lanka,1083.532030,1072.546602,1074.471960,1135.514326,1213.395530,1348.775651,1648.079789,1876.766827,2153.739222,2664.477257,3015.378833,3970.095407
Syria,1643.485354,2117.234893,2193.037133,1881.923632,2571.423014,3195.484582,3761.837715,3116.774285,3340.542768,4014.238972,4090.925331,4184.548089
Taiwan,1206.947913,1507.861290,1822.879028,2643.858681,4062.523897,5596.519826,7426.354774,11054.561750,15215.657900,20206.820980,23235.423290,28718.276840
Thailand,757.797418,793.577415,1002.199172,1295.460660,1524.358936,1961.224635,2393.219781,2982.653773,4616.896545,5852.625497,5913.187529,7458.396327
Vietnam,605.066492,676.285448,772.049160,637.123289,699.501644,713.537120,707.235786,820.799445,989.023149,1385.896769,1764.456677,2441.576404
West Bank and Gaza,1515.592329,1827.067742,2198.956312,2649.715007,3133.409277,3682.831494,4336.032082,5107.197384,6017.654756,7110.667619,4515.487575,3025.349798
Yemen Rep.,781.717576,804.830455,825.623201,862.442146,1265.047031,1829.765177,1977.557010,1971.741538,1879.496673,2117.484526,2234.820827,2280.769906

In [41]:
gdp_data.describe()

,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
count,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000,33.000000
mean,5195.484004,5787.732940,5729.369625,5971.173374,8187.468699,7791.314020,7434.135157,7608.226508,8639.690248,9834.093295,10174.090397,12473.026870
std,18634.890865,19506.515959,16415.857196,14062.591362,19087.502918,11815.777923,8701.176499,8090.262765,9727.431088,11094.180481,11150.719203,14154.937343
min,331.000000,350.000000,388.000000,349.000000,357.000000,371.000000,424.000000,385.000000,347.000000,415.000000,611.000000,944.000000
25%,749.681655,793.577415,825.623201,836.197138,1049.938981,1175.921193,1443.429832,1704.686583,1785.402016,1902.252100,2092.712441,2452.210407
50%,1206.947913,1547.944844,1649.552153,2029.228142,2571.423014,3195.484582,4106.525293,4106.492315,3726.063507,3645.379572,4090.925331,4471.061906
75%,3035.326002,3290.257643,4187.329802,5906.731805,8597.756202,11210.089480,12954.791010,11643.572680,15215.657900,19702.055810,19233.988180,22316.192870
max,108382.352900,113523.132900,95458.111760,80894.883260,109347.867000,59265.477140,33693.175250,28118.429980,34932.919590,40300.619960,36023.105400,47306.989780

In [42]:
gdp_data.loc['Bangladesh']

gdpPercap_1952     684.244172
gdpPercap_1957     661.637458
gdpPercap_1962     686.341554
gdpPercap_1967     721.186086
gdpPercap_1972     630.233627
gdpPercap_1977     659.877232
gdpPercap_1982     676.981866
gdpPercap_1987     751.979403
gdpPercap_1992     837.810164
gdpPercap_1997     972.770035
gdpPercap_2002    1136.390430
gdpPercap_2007    1391.253792
Name: Bangladesh, dtype: float64

In [43]:
gdp_bd = gdp_data.loc['Bangladesh']

In [44]:
gdp_bd.describe()

count      12.000000
mean      817.558818
std       235.079648
min       630.233627
25%       673.145764
50%       703.763820
75%       871.550132
max      1391.253792
Name: Bangladesh, dtype: float64

In [45]:
gdp_bd.round(decimals=2)

gdpPercap_1952     684.24
gdpPercap_1957     661.64
gdpPercap_1962     686.34
gdpPercap_1967     721.19
gdpPercap_1972     630.23
gdpPercap_1977     659.88
gdpPercap_1982     676.98
gdpPercap_1987     751.98
gdpPercap_1992     837.81
gdpPercap_1997     972.77
gdpPercap_2002    1136.39
gdpPercap_2007    1391.25
Name: Bangladesh, dtype: float64